name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Nerdbank.GitVersioning
        # You may pin to the exact commit or the version.
        # uses: dotnet/nbgv@1801854259a50d987aaa03b99b28cebf49faa779
        uses: dotnet/nbgv@v0.4.1
        id: nbgv
        # with:
        #   # The path to the directory for which the version should be determined. This should be at or below the directory containing the version.json file. Default is repo root directory.
        #   path: # optional, default is .
        #   # Defines ALL version variables as environment variables, with a "NBGV_" prefix.
        #   setAllVars: # optional
        #   # Defines a few common version variables as environment variables, with a "Git" prefix (e.g. GitBuildVersion, GitBuildVersionSimple, GitAssemblyInformationalVersion).
        #   setCommonVars: # optional
        #   # The path to a file whose version setting should be changed to match the computed version. Supported file types: `package.json`.
        #   stamp: # optional
        #   # The version of the nbgv dotnet CLI tool to install and use. If not specified, the default is the latest stable version.
        #   toolVersion: # optional
        #   # An additional feed to search for the nbgv dotnet CLI tool. Default feeds may include https://api.nuget.org/v3/index.json or whatever is specified in a nuget.config file at the root of your repo.
        #   toolFeed: # optional

      - name: Echo semver
        run: "echo ${{ steps.nbgv.outputs }}"

      - name: Echo 2
        run: |
          echo ${{ steps.nbgv.outputs.CloudBuildNumber }}
          echo ${{ steps.nbgv.outputs.VersionFileFound }}
          echo ${{ steps.nbgv.outputs.AssemblyVersion }}
          echo ${{ steps.nbgv.outputs.AssemblyFileVersion }}
          echo ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
          echo ${{ steps.nbgv.outputs.PublicRelease }}
          echo ${{ steps.nbgv.outputs.PrereleaseVersion }}
          echo ${{ steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen }}
          echo ${{ steps.nbgv.outputs.SimpleVersion }}
          echo ${{ steps.nbgv.outputs.BuildNumber }}
          echo ${{ steps.nbgv.outputs.VersionRevision }}
          echo ${{ steps.nbgv.outputs.MajorMinorVersion }}
          echo ${{ steps.nbgv.outputs.VersionMajor }}
          echo ${{ steps.nbgv.outputs.VersionMinor }}
          echo ${{ steps.nbgv.outputs.GitCommitId }}
          echo ${{ steps.nbgv.outputs.GitCommitIdShort }}
          echo ${{ steps.nbgv.outputs.GitCommitDate }}
          echo ${{ steps.nbgv.outputs.VersionHeight }}
          echo ${{ steps.nbgv.outputs.VersionHeightOffset }}
          echo ${{ steps.nbgv.outputs.Version }}
          echo ${{ steps.nbgv.outputs.BuildMetadataFragment }}
          echo ${{ steps.nbgv.outputs.NuGetPackageVersion }}
          echo ${{ steps.nbgv.outputs.ChocolateyPackageVersion }}
          echo ${{ steps.nbgv.outputs.NpmPackageVersion }}
          echo ${{ steps.nbgv.outputs.SemVer1 }}
          echo ${{ steps.nbgv.outputs.SemVer2 }}
            
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          image: shaurm/nodejs-cloud
          tags: latest, ${{ steps.nbgv.outputs.SemVer2 }}
